INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('powiekszonymagazynek', 'Udvidet Ammo', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('kompensator', 'Kompensator', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('MountedScope', 'Pistol Sigte', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('yusuf', 'Gold Skin', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('celownikdluga', 'Riffel Sigte', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('vipskinmotyl', 'VIP Skin Butterfly', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('kastetpink', 'Knuckle Skin LOVE', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('mediumscope', 'Medium Sigte', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('largescope', 'Stort Sigte', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('holografik', 'Holografisk Syn', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('platin50', 'Platinium Pistol 50 Skin', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('woodheavyp', 'Wood Heavy Pistol Skin', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('wooddlugie', 'Wood Rifles Skin', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('czaszkidlugie', 'Skull Rifles Skin', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('zebradlugie', 'Zebra Rifles Skin', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('boomdlugie', 'Boom Rifles Skin', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('tactitalmuzle', 'Tactical Muzzle Brake', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('kastetpimp', 'Knuckle Skin PIMP', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('kastetbalas', 'Knuckle Skin Ballas', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('kastetdollar', 'Knuckle Skin Dollar', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('kastetdiament', 'Knuckle Skin Diamond', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('kastethate', 'Knuckle Skin Hate', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('kastetplayer', 'Knuckle Skin Player', -1, 0, 1);
--INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('kastetvagos', 'Knuckle Skin Vagos', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('flashlight', 'Lygte', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('Suppressor', 'Lyddæmper', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('grip', 'Grip', -1, 0, 1);